linter:
  rules:
    avoid_positional_boolean_parameters: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    omit_local_variable_types: true
